from .register import Registers
from .model import social_stgcnn
from .model0 import social_stgcnn0
from .model1 import social_stgcnn1
from .model2 import social_stgcnn2
from .model3 import social_stgcnn3
from .model4 import social_stgcnn4
from .model5 import social_stgcnn5
from .model6 import social_stgcnn6
from .model7 import social_stgcnn7
from .model8 import social_stgcnn8
from .model9 import social_stgcnn9
from .model10 import social_stgcnn10
from .model11 import social_stgcnn11
from .model12 import social_stgcnn12
from .model13 import social_stgcnn13
from .model14 import social_stgcnn14
from .model15 import social_stgcnn15
from .model16 import social_stgcnn16
from .model17 import social_stgcnn17
from .model18 import social_stgcnn18
from .model19 import social_stgcnn19
from .model20 import social_stgcnn20
from .model21 import social_stgcnn21
from .model22 import social_stgcnn22
from .model23 import social_stgcnn23
from .model24 import social_stgcnn24
from .model25 import social_stgcnn25
from .model26 import social_stgcnn26
from .model27 import social_stgcnn27
from .model28 import social_stgcnn28
from .model29 import social_stgcnn29
from .ext_fea import social_stgcnn_ext
